### ISSUE TITLE
自动删除.aria2文件并没有生效

### ISSUE THREAD

**Issue by jiayaoO3O** [SuperNG6/docker-aria2#21]
文件已经下载完成, 并且已经做种完成, 进入了已完成列表 :
![image](https://user-images.githubusercontent.com/22891632/74096516-170b6d80-4b3b-11ea-9afc-315bd6a770c8.png)
但是本地文件夹文件还在 : 
![image](https://user-images.githubusercontent.com/22891632/74096528-2985a700-4b3b-11ea-8f97-95dfe13addf5.png)
![image](https://user-images.githubusercontent.com/22891632/74096497-e0cdee00-4b3a-11ea-8578-8bd311039d61.png)
![image](https://user-images.githubusercontent.com/22891632/74096505-f17e6400-4b3a-11ea-996c-5752f21397f7.png)

**Comment by SuperNG6** [comment]
`force-save=true`这个必须要有，否则重启aria2会丢失任务
如果下载目录是自定义的二级目录的话，是无法删除`.aria2`文件，这个我也无能为力

**Comment by jiayaoO3O** [comment]
巧了, 我真的就是定义了二级目录, 那我下一次下载改过来试试

**Comment by SuperNG6** [comment]
今天抽时间研究了一下aria2的参数传递，更新了删除文件的脚本，经过测试删除功能正常运行，删除功能已完善

**Comment by jiayaoO3O** [comment]
@SuperNG6 可以,那我重新拉一个 👍

**Comment by SuperNG6** [comment]
可以直接用watchtower：https://sleele.com/2019/06/16/docker更新容器镜像神器-watchtower/
在 2020年2月22日 +0800 PM1:16，jiayao <notifications@github.com>，写道：
