### ISSUE TITLE
Aria2重启后自动下载已完成的任务

### ISSUE THREAD

**Issue by xavier-niu** [SuperNG6/docker-aria2#24]
你好，目前使用latest镜像在重启后仍然存在重新下载已完成任务的问题，请问如何解决？谢谢！

**Comment by SuperNG6** [comment]
# 保存磁力链接元数据为种子文件(.torrent文件), 默认:false
bt-save-metadata=true
# 加载已保存的元数据文件，默认:false
bt-load-saved-metadata=true
保存磁力链接元数据为种子文件为 true。代价是会保存种子文件，且无法自动删除

在 2020年3月20日 +0800 PM6:43，XavierNiu <notifications@github.com>，写道：

**Comment by xavier-niu** [comment]
> # 保存磁力链接元数据为种子文件(.torrent文件), 默认:false bt-save-metadata=true # 加载已保存的元数据文件，默认:false bt-load-saved-metadata=true 保存磁力链接元数据为种子文件为 true。代价是会保存种子文件，且无法自动删除 在 2020年3月20日 +0800 PM6:43，XavierNiu <notifications@github.com>，写道：
> […](#)
> 你好，目前使用latest镜像在重启后仍然存在重新下载已完成任务的问题，请问如何解决？谢谢！ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

我没有使用BT，仅仅使用普通下载方式，我比较好奇的是什么机制使得他可以重启后自动下载呢？

**Comment by SuperNG6** [comment]
aria2自己的问题了，他可以自动保存，进度保存在session里，不是很完善
在 2020年3月20日 +0800 PM6:52，XavierNiu ，写道：

**Comment by xavier-niu** [comment]
OK 那看来临时的解决方式是把session关闭 后续我在研究一下 谢谢

**Comment by SuperNG6** [comment]
代价太大不建议，而且我这自动保存是正常的
在 2020年3月20日 +0800 PM7:02，XavierNiu <notifications@github.com>，写道：

**Comment by xavier-niu** [comment]
我这边是有个软件调用的aria2的api 所以我一开始觉得是不是有什么脚本没有调用导致的


----------------------------------------------
Xavier Niu
Email: a@nxw.name
Homepage: https://www.nxw.name

**Comment by xavier-niu** [comment]
我知道了 是因为在conf文件中`force-save=true`，这将导致已完成的任务在aria2退出前保存至`aria2.session`中，请问设置`force-save=true`的原因是？

**Comment by SuperNG6** [comment]
如果不开启`force-save=true`，会丢失下载进度的

**Comment by xavier-niu** [comment]
好的 谢谢
