### ISSUE TITLE
部分bt下载完成后,未能移动到completed文件夹

### ISSUE THREAD

**Issue by chaos700** [SuperNG6/docker-aria2#27]
mkdir: cannot create directory ‘ヨスガノソラ’: Permission denied
mkdir: cannot create directory ‘In’: Permission denied
mkdir: cannot create directory ‘solitude,’: Permission denied
mkdir: cannot create directory ‘where’: Permission denied
mkdir: cannot create directory ‘we’: Permission denied
mkdir: cannot create directory ‘are’: Permission denied
mkdir: cannot create directory ‘least’: Permission denied
mkdir: cannot create directory ‘alone’: Permission denied
05/10 13:38:03 [INFO] Move done: /downloads/[Snow-Raws] ヨスガノソラ In solitude, where we are least alone/Route -> /downloads/completed/[Snow-Raws] ヨスガノソラ In solitude, where we are least alone
05/10 13:38:04 [INFO] Clean up extra files ...
05/10 13:39:35 [INFO] Start move files ...

例如:https://share.dmhy.org/topics/view/540567_Snow-Raws_Yosuga_no_Sora_In_Solitude_Where_We_Are_Least_Alone_In_solitude_where_we_are_least_alone_BD_1920x1080_HEVC-YUV420P10_FLAC.html

看日志好像是权限问题,但我的UID和GID应该沒有填错,
而且其它bt下载都沒问题,可以正常移动到completed文件夹,
就是少数如上的下载未能移动,找不到失败的规律.

P.S. 用的是群晖的docker

**Comment by SuperNG6** [comment]
种子里的文件夹命名有问题，Linux对`/`是下一个目录，这个文件夹怎么会这么命名，这种无解了，文件夹名称太奇特
在 2020年5月10日 +0800 PM3:00，chaos700 <notifications@github.com>，写道：

**Comment by SuperNG6** [comment]
把种子下下来看了一下，这种情况应该是aria2下载的第一个文件是 `` [Snow-Raws] ヨスガノソラ In solitude, where we are least alone/Route/[Snow-Raws] ヨスガノソラ In solitude, where we are least alone. Route ``，Aria2传递的文件参数默认是第一个下载的文件，所以脚本里在去除路径的时候，就只去除了最末尾的文件，路径为 `` [Snow-Raws] ヨスガノソラ In solitude, where we are least alone/Route``导致移动失败，有空的时候研究一下这种情况怎么解决

**Comment by SuperNG6** [comment]
已修复，下载这类内部包含多个文件夹的复杂种子，下载时请手动选择对应目录`movies`,`tv`,`ani`  
https://github.com/SuperNG6/docker-aria2/pull/28  
![Xnip2020-05-11_15-43-56](https://cdn.jsdelivr.net/gh/SuperNG6/pic@master/uPic/Xnip2020-05-11_15-43-56.png)

**Comment by SuperNG6** [comment]
自动更新镜像
````
sudo docker run -d \
    --name watchtower_run_once \
    -e TZ=Asia/Shanghai \
    -v /var/run/docker.sock:/var/run/docker.sock \
    containrrr/watchtower --cleanup --run-once
````

**Comment by doream** [comment]
我用最新版的arm64版本跑在威联通里还是相同的情况，用admin账户的uid，完成的任务不自动移动到completed文件夹里，删除任务不移动到recycle文件夹里，日志输出[ERROR] Failed to get download directory!
