### ISSUE TITLE
建议 SSL 用常量控制开关

### ISSUE THREAD

**Issue by edwinhuish** [SuperNG6/docker-aria2#29]
非常好的一个docker镜像，正是我所需要的。

如题，建议 SSL 用常量控制开关。

**Comment by SuperNG6** [comment]
这个不好弄，要设置三个变量，如果不懂的人很容易弄的容器无法启动，给懂的人手动编辑conf文件吧
在 2020年6月5日 +0800 AM12:43，Edwin Hui <notifications@github.com>，写道：
