### ISSUE TITLE
下载磁力再下载种子文件之后出错：发生错误（13）

### ISSUE THREAD

**Issue by edwinhuish** [SuperNG6/docker-aria2#30]
请看下图，应该是下载完种子文件之后自动删除 .aria2 文件，导致无法继续进行下载导致的问题。

![image](https://user-images.githubusercontent.com/5207925/83856701-8b05fd00-a74c-11ea-81a9-d21ca6cab0cd.png)

**Comment by SuperNG6** [comment]
没有遇到过，可能是磁盘权限问题吧，建议检查一下磁盘权限
在 2020年6月5日 +0800 PM4:51，Edwin Hui <notifications@github.com>，写道：

**Comment by edwinhuish** [comment]
再次测试了其他磁力链接，没有这个问题。。估计是那个链接的问题。。。
