### ISSUE TITLE
下载任何类型文件出现： 发生错误（17） fallocate failed. cause: Operation not supported

### ISSUE THREAD

**Issue by zhk0603** [SuperNG6/docker-aria2#31]
部署在树莓派。下载路径挂载在了外接磁盘上。
docker 命令
```
docker create \
  --name=aria2 \
  -e PUID=0 \
  -e PGID=0 \
  -e TZ=Asia/Shanghai \
  -e SECRET=ariasecret \
  -e CACHE=512M \
  -e UpdateTracker=true \
  -e QUIET=true \
  -e RECYCLE=true \
  -e MOVE=true \
  -e SMD=false \
  -e ANIDIR=ani \
  -e MOVDIR=movies \
  -e TVDIR=tv \
  -e CUSDIR=cusdir \
  -p 6881:6881 \
  -p 6881:6881/udp \
  -p 6800:6800 \
  -p 9002:80 \
  -v /mnt/disk/aria2/config:/config \
  -v /mnt/disk/aria2/downloads:/downloads \
  --restart unless-stopped \
  superng6/aria2:webui-latest
```
下载磁力链接，跟普通链接都出现：
发生错误（17） fallocate failed. cause: Operation not supported

![image](https://user-images.githubusercontent.com/15643960/84900932-5e070200-b0dd-11ea-848a-dafe05abf871.png)

**Comment by SuperNG6** [comment]
看上去好像是不支持`falloc`,修改配置文件`file-allocation=falloc`为`file-allocation=none`看看
在 2020年6月17日 +0800 PM8:59，赵坤 <notifications@github.com>，写道：

**Comment by zhk0603** [comment]
哈哈。可以了。感谢！！！
![image](https://user-images.githubusercontent.com/15643960/84905177-e76d0300-b0e2-11ea-8d23-555409b40ef5.png)

![image](https://user-images.githubusercontent.com/15643960/84905220-f3f15b80-b0e2-11ea-822d-c115da0c3735.png)

**Comment by SuperNG6** [comment]
刚刚更新了一下，添加了磁盘预分配模式的选择，`-e FA=none`
