### ISSUE TITLE
都配置好了，也能连接但是Trackerlist没有更新？

### ISSUE THREAD

**Issue by lukemin** [SuperNG6/docker-aria2#32]
![image](https://user-images.githubusercontent.com/12003375/88262764-631e2900-ccfb-11ea-9153-8f757d455c6b.png)
什么情况，我可以自由访问github。

**Comment by SuperNG6** [comment]
我这边正常，可能是jsdelivr的网络抽风吧

**Comment by lukemin** [comment]
能不能多加几个更新的源吗？手动更新命令有吗？

**Comment by SuperNG6** [comment]
这个规则是最全的，加其他也只是重复添加
ariang里可以手动更新

lukemin <notifications@github.com>于2020年7月27日 周一上午8:38写道：

**Comment by lukemin** [comment]
> 能不能多加几个更新的源吗？手动更新命令有吗？
我的意思是tracker.sh能不能把github的注释取消了，只要jsdelivr.net或者github有一个可以更新就可以，防止只有一个源出现不能更新的情况。

**Comment by lukemin** [comment]
我收到运行tracker.sh 出现下面的错误tracker.sh: line 2: $'\r': command not found

 Get trackers ...

--------------------[TRACKERS]--------------------
http://00.mercax.com:443/announce,http://0205.uptm.ch:6969/announce,http://104.238.198.186:8000/announce,http://1337.abcvg.info:80/announce,http://178.175.143.27:80/announce,http://78.30.254.12:2710/announce,http://91.217.91.21:3218/announce,http://93.92.64.5:80/announce,http://[2001:1b10:1000:8101:0:242:ac11:2]:6969/announce,http://[2001:470:1:189:0:1:2:3]:6969/announce,http://[2a04:ac00:1:3dd8::1:2710]:2710/announce,http://aaa.army:8866/announce,http://atrack.pow7.com:80/announce,http://aws1.millegrilles.com:6969/announce,http://bandari.org:6969/announce,http://bobbialbano.com:6969/announce,http://bt.pusacg.org:8080/announce,http://dn42.smrsh.net:6969/announce,http://explodie.org:6969/announce,http://grifon.info:80/announce,http://h4.trakx.nibba.trade:80/announce,http://ns3107607.ip-54-36-126.eu:6969/announce,http://ns349743.ip-91-121-106.eu:80/announce,http://open.acgnxtracker.com:80/announce,http://open.acgtracker.com:1096/announce,http://open.touki.ru:80/announce.php,http://opentracker.i2p.rocks:6969/announce,http://pow7.com:80/announce,http://retracker.hotplug.ru:2710/announce,http://retracker.krs-ix.ru:80/announce,http://retracker.sevstar.net:2710/announce,http://retracker.spark-rostov.ru:80/announce,http://rt.tace.ru:80/announce,http://secure.pow7.com:80/announce,http://share.camoe.cn:8080/announce,http://t.acg.rip:6699/announce,http://t.nyaatracker.com:80/announce,http://t.overflow.biz:6969/announce,http://t1.pow7.com:80/announce,http://t2.pow7.com:80/announce,http://thetracker.org:80/announce,http://torrent.nwps.ws:80/announce,http://torrentsmd.com:8080/announce,http://torrenttracker.nwc.acsalaska.net:6969/announce,http://tr.cili001.com:8070/announce,http://tr.kxmp.cf:80/announce,http://tracker.anonwebz.xyz:8080/announce,http://tracker.birkenwald.de:6969/announce,http://tracker.bittor.pw:1337/announce,http://tracker.bt4g.com:2095/announce,http://tracker.bz:80/announce,http://tracker.dler.org:6969/announce,http://tracker.dutchtracking.nl:80/announce,http://tracker.files.fm:6969/announce,http://tracker.gbitt.info:80/announce,http://tracker.ipv6tracker.ru:80/announce,http://tracker.kuroy.me:5944/announce,http://tracker.lelux.fi:80/announce,http://tracker.moeking.me:6969/announce,http://tracker.nyap2p.com:8080/announce,http://tracker.opentrackr.org:1337/announce,http://tracker.publicbt.com:80/announce,http://tracker.sloppyta.co:80/announce,http://tracker.trackerfix.com:80/announce,http://tracker.tyker.xyz:8080/announce,http://tracker.uw0.xyz:6969/announce,http://tracker.ygsub.com:6969/announce,http://tracker.yoshi210.com:6969/announce,http://tracker.zum.bi:6969/announce,http://tracker1.itzmx.com:8080/announce,http://tracker2.dler.org:80/announce,http://tracker2.itzmx.com:6961/announce,http://tracker3.itzmx.com:6961/announce,http://trun.tom.ru:80/announce,http://update.cctvqueretaro.com:443/announce,http://vpn.flying-datacenter.de:6969/announce,http://vps02.net.orel.ru:80/announce,http://www.loushao.net:8080/announce,http://www.wareztorrent.com:80/announce,https://1337.abcvg.info:443/announce,https://2.tracker.eu.org:443/announce,https://3.tracker.eu.org:443/announce,https://aaa.army:8866/announce,https://opentracker.acgnx.se:443/announce,https://tr.ready4.icu:443/announce,https://tracker.bt-hash.com:443/announce,https://tracker.gbitt.info:443/announce,https://tracker.hama3.net:443/announce,https://tracker.imgoingto.icu:443/announce,https://tracker.jae.moe:443/announce,https://tracker.lelux.fi:443/announce,https://tracker.nanoha.org:443/announce,https://tracker.nitrix.me:443/announce,https://tracker.sloppyta.co:443/announce,https://tracker.tamersunion.org:443/announce,https://tracker.vectahosting.eu:2053/announce,https://tracker6.lelux.fi:443/announce,https://trakx.herokuapp.com:443/announce,https://w.wwwww.wtf:443/announce,udp://104.238.198.186:8000/announce,udp://107.150.14.110:6969/announce,udp://109.121.134.121:1337/announce,udp://114.55.113.60:6969/announce,udp://128.199.70.66:5944/announce,udp://151.80.120.114:2710/announce,udp://168.235.67.63:6969/announce,udp://178.33.73.26:2710/announce,udp://182.176.139.129:6969/announce,udp://185.5.97.139:8089/announce,udp://185.83.215.123:6969/announce,udp://185.86.149.205:1337/announce,udp://188.165.253.109:1337/announce,udp://191.101.229.236:1337/announce,udp://194.106.216.222:80/announce,udp://195.123.209.37:1337/announce,udp://195.123.209.40:80/announce,udp://208.67.16.113:8000/announce,udp://212.1.226.176:2710/announce,udp://212.47.227.58:6969/announce,udp://213.163.67.56:1337/announce,udp://37.19.5.155:2710/announce,udp://46.4.109.148:6969/announce,udp://47.ip-51-68-199.eu:6969/announce,udp://5.79.249.77:6969/announce,udp://5.79.83.193:6969/announce,udp://51.254.244.161:6969/announce,udp://52.58.128.163:6969/announce,udp://61626c.net:6969/announce,udp://62.138.0.158:6969/announce,udp://62.212.85.66:2710/announce,udp://6ahddutb1ucc3cp.ru:6969/announce,udp://74.82.52.209:6969/announce,udp://78.30.254.12:2710/announce,udp://85.17.19.180:80/announce,udp://89.234.156.205:80/announce,udp://9.rarbg.com:2710/announce,udp://9.rarbg.me:2710/announce,udp://9.rarbg.me:2780/announce,udp://9.rarbg.to:2710/announce,udp://9.rarbg.to:2730/announce,udp://91.216.110.52:451/announce,udp://91.218.230.81:6969/announce,udp://94.23.183.33:6969/announce,udp://95.211.168.204:2710/announce,udp://[2001:1b10:1000:8101:0:242:ac11:2]:6969/announce,udp://[2001:470:1:189:0:1:2:3]:6969/announce,udp://[2a03:7220:8083:cd00::1]:451/announce,udp://[2a04:ac00:1:3dd8::1:2710]:2710/announce,udp://[2a04:c44:e00:32e0:4cf:6aff:fe00:aa1]:6969/announce,udp://aaa.army:8866/announce,udp://admin.videoenpoche.info:6969/announce,udp://adminion.n-blade.ru:6969/announce,udp://api.bitumconference.ru:6969/announce,udp://aruacfilmes.com.br:6969/announce,udp://benouworldtrip.fr:6969/announce,udp://bitsparadise.info:6969/announce,udp://blokas.io:6969/announce,udp://bms-hosxp.com:6969/announce,udp://bt1.archive.org:6969/announce,udp://bt2.54new.com:8080/announce,udp://bt2.archive.org:6969/announce,udp://bubu.mapfactor.com:6969/announce,udp://cdn-1.gamecoast.org:6969/announce,udp://cdn-2.gamecoast.org:6969/announce,udp://chanchan.uchuu.co.uk:6969/announce,udp://chihaya.de:6969/announce,udp://chihaya.toss.li:9696/announce,udp://code2chicken.nl:6969/announce,udp://contra.sf.ca.us:6969/announce,udp://cpc69306-dudl11-0-0-cust33.16-1.cable.virginm.net:6969/announce,udp://cutiegirl.ru:6969/announce,udp://daveking.com:6969/announce,udp://discord.heihachi.pw:6969/announce,udp://dpiui.reedlan.com:6969/announce,udp://drumkitx.com:6969/announce,udp://eddie4.nl:6969/announce,udp://edenbridge.org.uk:6969/announce,udp://edu.uifr.ru:6969/announce,udp://eliastre100.fr:6969/announce,udp://engplus.ru:6969/announce,udp://exodus.desync.com:6969/announce,udp://exponage-api.com:6969/announce,udp://f68.n5022.z2.binkp.net:6969/announce,udp://fe.dealclub.de:6969/announce,udp://forever-tracker.zooki.xyz:6969/announce,udp://forever.publictracker.xyz:6969/announce,udp://free-tracker.zooki.xyz:6969/announce,udp://git.vulnix.sh:6969/announce,udp://gra1.joshkeegan.co.uk:6969/announce,udp://handrew.me:6969/announce,udp://inferno.demonoid.is:3391/announce,udp://ipv4.tracker.harry.lu:80/announce,udp://ipv6.tracker.zerobytes.xyz:16661/announce,udp://josueunhuit.com:6969/announce,udp://kanal-4.de:6969/announce,udp://kanbooru.com:6969/announce,udp://kawaii.social:6969/announce,udp://koli.services:6969/announce,udp://line-net.ru:6969/announce,udp://ln.mtahost.co:6969/announce,udp://mail.realliferpg.de:6969/announce,udp://mgtracker.org:2710/announce,udp://movies.zsw.ca:6969/announce,udp://mts.tvbit.co:6969/announce,udp://nagios.tks.sumy.ua:80/announce,udp://open.demonii.com:1337/announce,udp://open.stealth.si:80/announce,udp://opentor.org:2710/announce,udp://opentracker.i2p.rocks:6969/announce,udp://peerfect.org:6969/announce,udp://public-tracker.zooki.xyz:6969/announce,udp://public.popcorn-tracker.org:6969/announce,udp://public.publictracker.xyz:6969/announce,udp://publictracker.xyz:6969/announce,udp://qg.lorzl.gq:2710/announce,udp://retracker.akado-ural.ru:80/announce,udp://retracker.hotplug.ru:2710/announce,udp://retracker.lanta-net.ru:2710/announce,udp://retracker.local.msn-net.ru:6969/announce,udp://retracker.netbynet.ru:2710/announce,udp://retracker.nts.su:2710/announce,udp://retracker.sevstar.net:2710/announce,udp://rutorrent.frontline-mod.com:6969/announce,udp://sd-161673.dedibox.fr:6969/announce,udp://shadowshq.eddie4.nl:6969/announce,udp://shadowshq.yi.org:6969/announce,udp://storage.groupees.com:6969/announce,udp://t1.leech.ie:1337/announce,udp://t2.leech.ie:1337/announce,udp://t3.leech.ie:1337/announce,udp://teamspeak.value-wolf.org:6969/announce,udp://thetracker.org:80/announce,udp://threads.run:6969/announce,udp://tr.bangumi.moe:6969/announce,udp://tr.cili001.com:8070/announce,udp://tr2.ysagin.top:2710/announce,udp://tracker-udp.gbitt.info:80/announce,udp://tracker-v6.zooki.xyz:6969/announce,udp://tracker.0o.is:6969/announce,udp://tracker.aletorrenty.pl:2710/announce,udp://tracker.archlinux.org.theoks.net:6969/announce,udp://tracker.army:6969/announce,udp://tracker.beeimg.com:6969/announce,udp://tracker.birkenwald.de:6969/announce,udp://tracker.bittor.pw:1337/announce,udp://tracker.casual.run:6969/announce,udp://tracker.coppersurfer.tk:6969/announce,udp://tracker.cyberia.is:6969/announce,udp://tracker.dler.org:6969/announce,udp://tracker.ds.is:6969/announce,udp://tracker.dyne.org:6969/announce,udp://tracker.eddie4.nl:6969/announce,udp://tracker.ex.ua:80/announce,udp://tracker.filemail.com:6969/announce,udp://tracker.flashtorrents.org:6969/announce,udp://tracker.fortu.io:6969/announce,udp://tracker.gbitt.info:80/announce,udp://tracker.grepler.com:6969/announce,udp://tracker.halfchub.club:6969/announce,udp://tracker.iamhansen.xyz:2000/announce,udp://tracker.internetwarriors.net:1337/announce,udp://tracker.kuroy.me:5944/announce,udp://tracker.leechers-paradise.org:6969/announce,udp://tracker.lelux.fi:6969/announce,udp://tracker.moeking.me:6969/announce,udp://tracker.open-internet.nl:6969/announce,udp://tracker.openbittorrent.com:80/announce,udp://tracker.opentrackr.org:1337/announce,udp://tracker.piratepublic.com:1337/announce,udp://tracker.publicbt.com:80/announce,udp://tracker.shkinev.me:6969/announce,udp://tracker.skynetcloud.site:6969/announce,udp://tracker.skyts.net:6969/announce,udp://tracker.swateam.org.uk:2710/announce,udp://tracker.teambelgium.net:6969/announce,udp://tracker.tiny-vps.com:6969/announce,udp://tracker.torrent.eu.org:451/announce,udp://tracker.tvunderground.org.ru:3218/announce,udp://tracker.uw0.xyz:6969/announce,udp://tracker.v6speed.org:6969/announce,udp://tracker.vulnix.sh:6969/announce,udp://tracker.yoshi210.com:6969/announce,udp://tracker.zemoj.com:6969/announce,udp://tracker.zerobytes.xyz:1337/announce,udp://tracker.zooki.xyz:6969/announce,udp://tracker.zum.bi:6969/announce,udp://tracker0.ufibox.com:6969/announce,udp://tracker1.itzmx.com:8080/announce,udp://tracker2.christianbro.pw:6969/announce,udp://tracker2.dler.org:80/announce,udp://tracker2.indowebster.com:6969/announce,udp://tracker2.itzmx.com:6961/announce,udp://tracker3.itzmx.com:6961/announce,udp://tracker4.itzmx.com:2710/announce,udp://tracker6.dler.org:2710/announce,udp://u.wwwww.wtf:1/announce,udp://ultra.zt.ua:6969/announce,udp://valakas.rollo.dnsabr.com:2710/announce,udp://vibe.community:6969/announce,udp://www.loushao.net:8080/announce,udp://www.midea123.z-media.com.cn:6969/announce,udp://z.mercax.com:53/announce,udp://zephir.monocul.us:6969/announce,udp://zer0day.ch:1337/announce,udp://zer0day.to:1337/announce
--------------------[TRACKERS]--------------------

' ...ng trackers to '/config/aria2.conf
tracker.sh: line 19: $'echo\r': command not found
tracker.sh: line 26: syntax error near unexpected token `fi'
tracker.sh: line 26: `fi'

**Comment by SuperNG6** [comment]
测试了一下，我这一切正常，你是在容器里执行的么？
![UlRD1J](https://gitee.com/sleele/pic/raw/master/uPic/2020-07-27/UlRD1J.png)

**Comment by lukemin** [comment]
> 测试了一下，我这一切正常，你是在容器里执行的么？
> ![UlRD1J](https://camo.githubusercontent.com/fcf60d74f26ab4a662b711f2f12400108277985c/68747470733a2f2f67697465652e636f6d2f736c65656c652f7069632f7261772f6d61737465722f755069632f323032302d30372d32372f556c5244314a2e706e67)
出错原因找到了，config的位置我忘记换了，现在运行没问题了
![image](https://user-images.githubusercontent.com/12003375/88498284-4df41380-cff5-11ea-8129-33e8982e9032.png)
但是容器开启的时候不能，更新tracker，提示网络错误

**Comment by SuperNG6** [comment]
> 测试了一下，我这一切正常，你是在容器里执行的么？
> ![UlRD1J]
> 在容器中执行需要什么命令？(https://camo.githubusercontent.com/fcf60d74f26ab4a662b711f2f12400108277985c/68747470733a2f2f67697465652e636f6d2f736c65656c652f7069632f7261772f6d61737465722f755069632f323032302d30372d32372f556c5244314a2e706e67)
> 出错原因找到了，config的位置我忘记换了，现在运行没问题了
> ![image](https://user-images.githubusercontent.com/12003375/88498284-4df41380-cff5-11ea-8129-33e8982e9032.png)
> 但是容器开启的时候不能，更新tracker，提示网络错误

今天更新增加了通过rpc的方式更新trackers，并且有多个tracker地址，防止单个地址无法访问时的trackers更新失败
