### ISSUE TITLE
文件过滤好像不起作用

### ISSUE THREAD

**Issue by woboo110** [SuperNG6/docker-aria2#34]
文件过滤好像不起作用，我设置的150M，但是下载完成后并没有删除没用文件，难道是没有权限？？

是不是要重启？

![QQ图片20210218145447](https://user-images.githubusercontent.com/68997087/108317789-c0c71500-71f9-11eb-8277-f610ee96e1ea.png)

**Comment by SuperNG6** [comment]
# 号注释删掉，我这边测试正常

**Comment by woboo110** [comment]
> `# 号`注释删掉，然后设置里开启文件过滤。我这边测试正常

#号删了，设置里开启文件过滤没弄， 我找找
