### ISSUE TITLE
tracker地址、更新时间如何变更？

### ISSUE THREAD

**Issue by woboo110** [SuperNG6/docker-aria2#35]
需要自己建script文件夹，把脚本还有设置文件上传到配置目录吗？我建好容器后没有script文件夹

![1](https://user-images.githubusercontent.com/68997087/108587727-3e248e00-7390-11eb-9f99-0444e0262e6d.png)
![2](https://user-images.githubusercontent.com/68997087/108587729-3fee5180-7390-11eb-806c-4b3036272350.png)

**Comment by SuperNG6** [comment]
1、不支持设置更新时间
2、script文件夹在容器内部，不需要任何配置，更新随着容器更新而自动更新

**Comment by woboo110** [comment]
> 1、不支持设置更新时间
> 2、script文件夹在容器内部，不需要任何配置，更新随着容器更新而自动更新

好的，感谢解答，很好用
