### ISSUE TITLE
关于启用 ipv6

### ISSUE THREAD

**Issue by YeC1213** [SuperNG6/docker-aria2#38]
能否默认启用ipv6相关功能，当前需要手动修改配置

**Comment by SuperNG6** [comment]
不会默认开启ipv6相关功能，目前docker桥接模式下ipv6问题挺多的，host模式好些，有需要的手动修改一下配置文件就可以，不麻烦

**Comment by x1737886903** [comment]
请问怎么修改ipv6配置？
目前没有ipv4的公网ip，只能用ipv6绑定域名，有什么需要注意的事项

**Comment by lyrnya** [comment]
> 请问怎么修改ipv6配置？ 目前没有ipv4的公网ip，只能用ipv6绑定域名，有什么需要注意的事项

在容器内或者绑定config目录内修改aria2.conf
```
# 禁用IPv6, 默认:false
disable-ipv6=false

# DHT（IPv6）文件
dht-file-path6=/config/dht6.dat

# 打开IPv6 DHT功能, PT需要禁用
enable-dht6=true
```
