### ISSUE TITLE
网页如何设置ssl？

### ISSUE THREAD

**Issue by pipidaxian** [SuperNG6/docker-aria2#39]
已经成功的设置了RPC的https，请问这个web网页如何设置证书用https访问呢？

**Comment by SuperNG6** [comment]
设置这几个地方
![tLk2O8](https://cdn.jsdelivr.net/gh/SuperNG6/pic@master/uPic/2021-09-18/tLk2O8.png)

**Comment by pipidaxian** [comment]
我这个已经设置好了，rpc（6800端口）可以用https连接上，但是我的这个网页（8080端口）还是只能http进，显示不安全

**Comment by pipidaxian** [comment]
就是这个地方因为没有证书显示不安全，只能用http登录
![Uploading 5516190E-74B8-41B6-9E50-77ADAF7B8597.jpeg…]()

**Comment by SuperNG6** [comment]
https://sleele.com/2019/09/12/群辉dsm自带反向代理教程/
