### ISSUE TITLE
webui未能成功连接aria2

### ISSUE THREAD

**Issue by ShiverZm** [SuperNG6/docker-aria2#57]
![截图_20221021145740](https://user-images.githubusercontent.com/26861023/197132699-0766eb50-8f45-4794-9439-ea186c8a8b85.png)

**Comment by ShiverZm** [comment]
docker run -d \
  --name=aria2 \
  --privileged=true \
  -e PUID=0 \
  -e PGID=0 \
  -e TZ=Asia/Shanghai \
  -e SECRET=123456 \
  -e CACHE=512M \
  -e PORT=6800 \
  -e BTPORT=32516 \
  -e WEBUI=true \
  -e WEBUI_PORT=8080 \
  -e UT=true \
  -e RUT=true \
  -e FA=falloc \
  -e QUIET=true \
  -e SMD=true \
  -p 6881:6881 \
  -p 6881:6881/udp \
  -p 6800:6800 \
  -p 8080:8080 \
  -v $PWD/config:/config \
  -v $PWD/downloads:/downloads \
  superng6/aria2:webui-latest

**Comment by ShiverZm** [comment]
已解决
1.进入0.0.0.0:8080 找到AriaNg设置->RPC(0.0.0.0:8080)
![截图_20221021170922](https://user-images.githubusercontent.com/26861023/197159241-4148b494-38da-4df8-aaee-a4fd2bb022c3.png)

2.修改Aria2 RPC地址为 localhost
(如果设置了RPC密钥的话记得填上去  我就是忘了填写)  
![截图_20221021171038](https://user-images.githubusercontent.com/26861023/197159431-f94daf5e-e738-4bae-8691-0a0500706ac7.png)

**Comment by SuperNG6** [comment]
webui里设置aria2服务器地址
![LJiM7x](https://cdn.jsdelivr.net/gh/SuperNG6/pic@master/uPic/2022-10-21/LJiM7x.png)

**Comment by ShiverZm** [comment]
@SuperNG6 顺便一问 大佬为何下载速度一直不动
![截图_20221021171516](https://user-images.githubusercontent.com/26861023/197160374-6271c083-6fb3-4f24-9ee3-16811db5861b.png)

**Comment by SuperNG6** [comment]
取决于资源，如果能够连接到更多的资源上传者那么速度才能变快
在 2022年10月21日 +0800 17:15，Shiver ***@***.***>，写道：
