### ISSUE TITLE
今天最新的 Docker 镜像运行有问题

### ISSUE THREAD

**Issue by uglyboy-tl** [SuperNG6/docker-aria2#64]
运行命令增加了一个 `--config" "/etc/wireproxy/config`
但镜像无对应文件，导致启动失败

**Comment by SuperNG6** [comment]
晕了，另外一个仓库的
https://github.com/SuperNG6/wireproxy/blob/master/.github/workflows/Build%20Image.yml
![uWsMl8](https://cdn.jsdelivr.net/gh/SuperNG6/pic@master/uPic/2023-04-12/uWsMl8.png)

**Comment by uglyboy-tl** [comment]
嗯，现在已经OK了
