### ISSUE TITLE
AriaNG无法从ipv6地址访问

### ISSUE THREAD

**Issue by lyrnya** [SuperNG6/docker-aria2#75]
容器网络模式为host
进入容器修改aria.conf启用ipv6
防火墙已经打开6800和8080端口
Aria RPC可以从外网连接
![_-1373529137__0a5d1698092dcf2fcc0b9e212989a9e5_-16524522_S40223-10525052_0_xg_0](https://github.com/SuperNG6/docker-aria2/assets/92076022/b6ccbb3a-d08f-4438-b85b-7b5baaddc937)
但是AriaNG无法从外网访问
请教如何修改使UI网页也能从ipv6打开

**Comment by boxhz** [comment]
图中使用的是在线AriaNG
