### ISSUE TITLE
最新版本容器aria2b似乎没有启动

### ISSUE THREAD

**Issue by lyrnya** [SuperNG6/docker-aria2#82]
![图片](https://github.com/user-attachments/assets/ccec1a50-8289-48c4-b4cd-48ce8369d3c0)
启动后看不到与屏蔽相关的内容，上一个版本的容器superng6/aria2:a2b-stable-23-12-06是正常的

**Comment by SuperNG6** [comment]
已修复，拉取最新镜像即可
