### ISSUE TITLE
Any plan to update Aria2?

### ISSUE THREAD

**Issue by vampywiz17** [SuperNG6/docker-aria2#83]
The latest version are 1.37.0

You plan to update it inside container?

Strange because your dockerfile are check these method to the version:

wget -qO- https://api.github.com/repos/mayswind/AriaNg/tags | grep 'name' | cut -d\" -f4 | head -1 

The result is 1.37.0, so i dont know why use the container the 1.36.0 version. (the "latest" tag)

**Comment by SuperNG6** [comment]
Updated

**Comment by vampywiz17** [comment]
@SuperNG6 

I checked the latest docker image, but seems also use 1.36
