### ISSUE TITLE
是否支持使用其他设备上的种子文件进行下载？

### ISSUE THREAD

**Issue by Giresharu** [SuperNG6/docker-aria2#85]
我在其他机器上使用webui，选择新建-打开种子文件，此时会提示“无法连接到 Aria2”
但是实际上是已经连接到的，其他下载行为也可以正常进行。

这个现象是正常的吗？

**Comment by SuperNG6** [comment]
没有遇到过这种情况，有日志吗

**Comment by Giresharu** [comment]
> 没有遇到过这种情况，有日志吗

最近重装了一下linux再装docker-aria2就没发现这个状况了，可能是系统网络配置方面的问题吧。
